### ISSUE TITLE
remove boostrap

### ISSUE THREAD

**Issue by bolom** [lobo-studio/goyava.io#5]

**Comment by bolom** [comment]
@accetone do you think you should keep boostrap?

**Comment by accetone** [comment]
@bolom we can remove bootstrap, but this will require some time to rewrite existing layout. Main question is - why you need this? 

If you want to reduce page size, there is an option to use only required things from bootstrap (here we can customize bootstrap.css http://getbootstrap.com/customize/).

If you have another goal - let me know, I will think about it.

**Comment by bolom** [comment]
it was just a question. if it's not necessary. let move on
